/**
 * icons.tsx — Re-exports common icons used across ShopFlow
 * Centralises icon imports so pages don't need to know which lib each comes from.
 */
import {
  Loader2,
  AlertCircle,
  CheckCircle2,
  XCircle,
  Eye,
  EyeOff,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ArrowRight,
  ArrowLeft,
  Plus,
  Minus,
  X,
  Check,
  Search,
  Settings,
  User,
  Mail,
  Lock,
  Bell,
  Home,
  LogOut,
  Sun,
  Moon,
  Menu,
  MoreHorizontal,
  MoreVertical,
  Edit,
  Trash2,
  Copy,
  Download,
  Upload,
  ExternalLink,
  RefreshCcw,
  Filter,
  SortAsc,
  SortDesc,
  Wrench,
  Car,
  FileText,
  CreditCard,
  Package,
  Users,
  BarChart3,
  Calendar,
  MessageCircle,
} from "lucide-react";

// FcGoogle from react-icons (used in login/register for Google OAuth button)
export { FcGoogle } from "react-icons/fc";

export const Icons = {
  spinner: Loader2,
  alertCircle: AlertCircle,
  checkCircle: CheckCircle2,
  xCircle: XCircle,
  eye: Eye,
  eyeOff: EyeOff,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  plus: Plus,
  minus: Minus,
  close: X,
  check: Check,
  search: Search,
  settings: Settings,
  user: User,
  mail: Mail,
  lock: Lock,
  bell: Bell,
  home: Home,
  logout: LogOut,
  sun: Sun,
  moon: Moon,
  menu: Menu,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  edit: Edit,
  trash: Trash2,
  copy: Copy,
  download: Download,
  upload: Upload,
  externalLink: ExternalLink,
  refresh: RefreshCcw,
  filter: Filter,
  sortAsc: SortAsc,
  sortDesc: SortDesc,
  wrench: Wrench,
  car: Car,
  fileText: FileText,
  creditCard: CreditCard,
  package: Package,
  users: Users,
  barChart: BarChart3,
  calendar: Calendar,
  message: MessageCircle,
};

export type Icon = keyof typeof Icons;
